services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: web2-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=pass@wowrd1234
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - C:\Demos\Data:/var/opt/mssql/data
    restart: unless-stopped